### ISSUE TITLE
Hellebore outputting maximum signal on patch reopening

### ISSUE THREAD

**Issue by subtleshift** [LeNomDesFleurs/NOI-VCVRACK#4]
Hello Thomas, I'm getting an extremely hot signal out of Hellebore after closing and reopening a patch that contains it - not sure if it relates to having CV (+/-5v) on the size and variation inputs

![hellebore test](https://user-images.githubusercontent.com/51462301/223887891-58108a44-22e9-4d03-b9b8-cc900425bebf.png)

VCV Rack Free 2.2.3 on windows 10 x64
Best regards, John

**Comment by LeNomDesFleurs** [comment]
Thanks for your input !
I'll work on that and come back to you

**Comment by LeNomDesFleurs** [comment]
I've pushed and update with better buffer initialisation
should arrive in a few days, tell me if it happen again
Have a nice day !
