### ISSUE TITLE
hellebore outputs high voltage

### ISSUE THREAD

**Issue by docb** [LeNomDesFleurs/NOI-VCVRACK#5]
commit da35d3128bb77fb5a8c9255c4f14b028c45131dd

![hellebore](https://user-images.githubusercontent.com/1134412/225260846-65d7863d-7fd7-4dbb-986b-64b9cf494342.png)

**Comment by LeNomDesFleurs** [comment]
Hello,
thanks for sharing !
Do you have any information on how it happened ?
Do closing and relaunching vcv solve the problem ?

**Comment by docb** [comment]
hi, unfortunately i cannot reproduce the behavior any more. 
- edit: one time i loaded it and the right output had NAN, another time it had high voltage (without any input connected)
sorry, this is not reproducible at all and there are no obvious reasons for the behavior.

**Comment by LeNomDesFleurs** [comment]
The module is widely unstable, based mostly on feedback
I'm in the process of rewriting the whole code in the hope to make it more stable.
What you see is common behaviour as of now, I'm trying to fix it but I struggle to pinpoint the source of the problem.
I'll keep working, thanks for the feedback !

**Comment by qwitwa** [comment]
bro my ears :(

slap some kind of killswitch or limiter on this

![image](https://github.com/LeNomDesFleurs/NOI-VCVRACK/assets/2302478/d61932cb-fb7b-40d3-80a3-4bf939b2750f)

**Comment by LeNomDesFleurs** [comment]
Ah shit, awfully sorry for this, I'm pushing an update right now

**Comment by qwitwa** [comment]
Legend :)

**Comment by LeNomDesFleurs** [comment]
It should be clipped to -6/6, + some buffer safeguard that kills high values.
It might still derail, come back to me if it happen again !
