### ISSUE TITLE
Integration issues

### ISSUE THREAD

**Issue by cschol** [LeNomDesFleurs/NOI-VCVRACK#7]
There are a few issues with the plugin version `2.0.5`:

- `*.dylib` binary committed to repository. Please remove from repository, including repo history using a tool like `BFGCleaner`.
- `Makefile` contains hardcoded `RACK_DIR`. This breaks the Rack build system. You should set the `RACK_DIR` environment variable outside of the Makefile to point to your Rack location.

**Comment by LeNomDesFleurs** [comment]
Hi, 
sorry for the mistakes, should be fixed, tell me if it is ok for you.

**Comment by cschol** [comment]
There are some debug `printf` statements that should be removed:

![image](https://github.com/LeNomDesFleurs/NOI-VCVRACK/assets/624427/870ca8a9-5b85-434f-8d4f-8d8e8316a163)

In `buffer.cpp` and `reverb.cpp`.

**Comment by LeNomDesFleurs** [comment]
Fixed, thank you
