### ISSUE TITLE
Input to control Dry/Wet

### ISSUE THREAD

**Issue by IohannRabeson** [LeNomDesFleurs/NOI-VCVRACK#8]
Hi! It could be great if there were an input available to control the dry/wet parameter.

**Comment by LeNomDesFleurs** [comment]
Hi! Thanks for reaching me
In which module would you like to see this feature ?

**Comment by IohannRabeson** [comment]
Hi! Yeah sorry about that i forgot to mention it was about Hellebore.

**Comment by LeNomDesFleurs** [comment]
The knob at the bottom is supposed to be a dry wet haha 😅
I think it got a bit messy with all the delay and filter involved, there is probably some phase issue when the dry and wet signal get mixed

I'll see what I can do, don't hesitate if you have any advice

**Comment by IohannRabeson** [comment]
I would add an input to control the dry/wet parameter.

**Comment by LeNomDesFleurs** [comment]
Done !
update should be available in a week or so
I don't have the space for a cv trimpot, I'll be up to you to scale you cv
Modulation is relative, dry wet goes from 0. to 1., the cv adds it's value divided by five.
e.g. dry wet = 0.5, cv = -3v
0.5 - (3 / 5) = -0.1 (clipped to 0.0), so full dry
I'll close the issue but open up any time if you have more questions
